version: '3.8'

services:
  database:
    image: postgres:15.7
    container_name: tesi-container
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=202011399
      - POSTGRES_DB=tesi
    volumes:
      - ./postgres:/var/lib/postgresql/data